[common]
quiet = true
# debug = true
# debug_file = "~/.local/state/toot.log"

[commands.tui]
colors = 16777216
image_format = "kitty"
media_viewer = "kitten icat --clear --unicode-placeholder"

[tui.palette]
"status_list_selected" = ["white,bold", "", "bold,underline"]
