# https://coolors.co/712fff

background=""
text="#F5F5F4"
subtle="#90A4AE"

warning-text="#712FFF"
top-bar-background="#712FFF"
status-bar-background="#712FFF"
list-selected-background="#712FFF"
button-color-one="#712FFF"
text-special-one="#7A3DFF"

top-bar-text="#F5F5F4"
status-bar-text="#F5F5F4"
status-bar-view-text="#F5F5F4"
command-text="#F5F5F4"
list-selected-text="#F5F5F4"
list-selected-inactive-text="#22252F"
controls-text="#F5F5F4"
autocomplete-text="#F5F5F4"
autocomplete-selected-text="#F5F5F4"

status-bar-view-background="#F5F5F4"
list-selected-inactive-background="#F5F5F4"
autocomplete-selected-background="#F5F5F4"

text-special-two="#B2FF59"
controls-highlight="#B2FF59"

autocomplete-background="#272822"
button-color-two="#272822"
timeline-name-background="#272822"

timeline-name-text="#B0BEC5"
